WIDTH = 800
HEIGHT = 600
FPS = 30

SPRITE_DIRECTION_SIZE = 4

DIRECTION_UP = 0
DIRECTION_RIGHT = 1
DIRECTION_DOWN = 2
DIRECTION_LEFT = 3
DIRECTION_UP_RIGHT = 4
DIRECTION_UP_LEFT = 5
DIRECTION_DOWN_RIGHT = 6
DIRECTION_DOWN_LEFT = 7

Coord = tuple[int, int]

